### ISSUE TITLE
gtk or gtk3

### ISSUE THREAD

**Issue by tony37** [cristian99garcia/tuxmath-activity#4]
The commit messages say 'return to gtk2'; however the code of activity.py imports sugar3.

**Comment by rhl-bthr** [comment]
Thanks, agreed that the message for 586914bad59bcc56a32d4d63c1e98e961abd4f00 is incorrect. But, I don't think we can do anything about it.

FWIW, the activity was ported to GTK+ 3 in f811c3a20452d2b5eda8f336f8d8901990078287
